import { Inter } from "next/font/google";
// import Image from "next/image";

import "../styles/globals.scss";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
// import img1 from "../public/img1.jpg";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main>{children}</main>
        {/* <div className="img">
          <Image src={img1} alt="Picture" placeholder="blur" />
        </div> */}
        <Footer />
      </body>
    </html>
  );
}
